flowchart TD
  N1[&lt;anonymous&gt;]
  N2[GetMediaProcessingStatusCliHandler]
  N3[ContinuePublicationAfterMediaSucceededCmd.Handler]
  N4[ContinuePublicationAfterMediaSucceededCmd.Request]
  N5[MarkMediaProcessingSucceededCmd.Handler]
  N6[MarkMediaProcessingSucceededCmd.Request]
  N7[StartMediaProcessingCmd.Handler]
  N8[StartMediaProcessingCmd.Request]
  N9[GetMediaProcessingStatusCli.Request]
  N10[ContentDraftCreatedDomainEventSubscriber::on]
  N11[ContentPublishedDomainEventSubscriber::on]
  N12[ContentReviewApprovedDomainEventSubscriber::onContentReviewApproved]
  N13[ContentSubmittedForReviewDomainEventSubscriber::on]
  N14[MediaProcessingSucceededDomainEventSubscriber::onMediaProcessingSucceeded]
  N15[Content::&lt;get-id&gt;]
  N16[Content::&lt;get-mediaSourceKey&gt;]
  N17[Content::&lt;get-releasePolicy&gt;]
  N18[Content::&lt;get-releaseWindowClosesAt&gt;]
  N19[Content::&lt;get-releaseWindowOpensAt&gt;]
  N20[ContentDraftCreatedDomainEvent]
  N21[ContentPublishedDomainEvent]
  N22[ContentReviewApprovedDomainEvent]
  N23[ContentSubmittedForReviewDomainEvent]
  N24[MediaProcessingTask::&lt;get-externalTaskId&gt;]
  N25[MediaProcessingTask::&lt;get-id&gt;]
  N26[MediaProcessingTask::&lt;get-processingStatus&gt;]
  N27[MediaProcessingTask::markSubmitted]
  N28[MediaProcessingTask::markSucceeded]
  N29[MediaProcessingTask::onCreate]
  N30[MediaProcessingSucceededDomainEvent]
  N1 -->|CommandSenderMethodToCommand| N6
  N1 -->|CliSenderMethodToCli| N9
  N1 -->|EntityMethodToDomainEvent| N20
  N1 -->|EntityMethodToDomainEvent| N21
  N1 -->|EntityMethodToDomainEvent| N22
  N1 -->|EntityMethodToDomainEvent| N23
  N1 -->|EntityMethodToDomainEvent| N30
  N3 -->|CommandHandlerToEntityMethod| N17
  N3 -->|CommandHandlerToEntityMethod| N18
  N3 -->|CommandHandlerToEntityMethod| N19
  N4 -->|CommandToCommandHandler| N3
  N5 -->|CommandHandlerToEntityMethod| N24
  N5 -->|CommandHandlerToEntityMethod| N25
  N5 -->|CommandHandlerToEntityMethod| N26
  N5 -->|CommandHandlerToEntityMethod| N28
  N6 -->|CommandToCommandHandler| N5
  N7 -->|CommandHandlerToEntityMethod| N15
  N7 -->|CommandHandlerToEntityMethod| N16
  N7 -->|CommandHandlerToEntityMethod| N27
  N7 -->|CommandHandlerToEntityMethod| N29
  N8 -->|CommandToCommandHandler| N7
  N9 -->|CliToCliHandler| N2
  N12 -->|DomainEventHandlerToCommand| N8
  N14 -->|DomainEventHandlerToCommand| N4
  N20 -->|DomainEventToHandler| N10
  N21 -->|DomainEventToHandler| N11
  N22 -->|DomainEventToHandler| N12
  N23 -->|DomainEventToHandler| N13
  N28 -->|EntityMethodToDomainEvent| N30
  N30 -->|DomainEventToHandler| N14

