flowchart TD
  N1[ConfirmManualReleaseCmd.Handler::exec]
  N2[RetryPublicationReleaseSagaCmd.Request]
  N3[PublicationReleaseReadiness::&lt;get-releaseSagaId&gt;]
  N4[PublicationReleaseReadiness::canRetryReleaseSaga]
  N1 -->|CommandSenderMethodToCommand| N2
  N2 -->|CommandToEntityMethod| N3
  N2 -->|CommandToEntityMethod| N4

