flowchart TD
  N1[GetMediaProcessingStatusQryHandler]
  N2[QueryController::getMediaProcessing]
  N3[GetMediaProcessingStatusQry.Request]
  N2 -->|ControllerMethodToQuery| N3
  N3 -->|QueryToQueryHandler| N1

