flowchart TD
  N1[AdvancedReleaseReadinessController::confirmManual]
  N2[ConfirmManualReleaseCmd.Request]
  N3[TryContinuePublicationReleaseCmd.Request]
  N4[ManualReleaseConfirmedDomainEventSubscriber::tryContinuePublicationRelease]
  N5[PublicationReleaseReadiness::confirmManualRelease]
  N6[ManualReleaseConfirmedDomainEvent]
  N1 -->|ControllerMethodToCommand| N2
  N2 -->|CommandToEntityMethod| N5
  N4 -->|DomainEventHandlerToCommand| N3
  N5 -->|EntityMethodToDomainEvent| N6
  N6 -->|DomainEventToHandler| N4

