flowchart TD
  N1[MarkMediaProcessingSucceededCmd.Request]
  N2[MediaProcessingCallbackIntegrationEventSubscriber::markMediaProcessingSucceeded]
  N3[MediaProcessingCallbackIntegrationEvent]
  N2 -->|IntegrationEventHandlerToCommand| N1
  N3 -->|IntegrationEventToHandler| N2

