flowchart TD
  N1[PublishContentCmd.Request]
  N2[PublishPaidPublicationContentCmd.Handler::exec]
  N3[ContentPublishedDomainEventSubscriber::on]
  N4[Content::&lt;get-releasePolicy&gt;]
  N5[Content::publish]
  N6[ContentPublishedDomainEvent]
  N1 -->|CommandToEntityMethod| N4
  N1 -->|CommandToEntityMethod| N5
  N2 -->|CommandSenderMethodToCommand| N1
  N5 -->|EntityMethodToDomainEvent| N6
  N6 -->|DomainEventToHandler| N3
