flowchart TD
  N1[ReviewController::approve]
  N2[ApproveContentReviewCmd.Request]
  N3[StartMediaProcessingCmd.Request]
  N4[ContentRequiresMediaProcessingDomainEventSubscriber::on]
  N5[Content::approve]
  N6[ContentRequiresMediaProcessingDomainEvent]
  N7[ContentReviewApprovedDomainEvent]
  N8[MediaProcessingTask::&lt;get-processingStatus&gt;]
  N9[MediaProcessingTask::markSubmitted]
  N10[MediaProcessingTask::onCreate]
  N1 -->|ControllerMethodToCommand| N2
  N2 -->|CommandToEntityMethod| N5
  N3 -->|CommandToEntityMethod| N8
  N3 -->|CommandToEntityMethod| N9
  N3 -->|CommandToEntityMethod| N10
  N4 -->|DomainEventHandlerToCommand| N3
  N5 -->|EntityMethodToDomainEvent| N6
  N5 -->|EntityMethodToDomainEvent| N7
  N6 -->|DomainEventToHandler| N4
