flowchart TD
  N1[ReviewController::submitReview]
  N2[SubmitContentForReviewCmd.Handler]
  N3[SubmitContentForReviewCmd.Request]
  N4[ContentSubmittedForReviewDomainEventSubscriber::on]
  N5[Content::submitForReview]
  N6[ContentSubmittedForReviewDomainEvent]
  N1 -->|ControllerMethodToCommand| N3
  N2 -->|CommandHandlerToEntityMethod| N5
  N3 -->|CommandToCommandHandler| N2
  N5 -->|EntityMethodToDomainEvent| N6
  N6 -->|DomainEventToHandler| N4

