flowchart TD
  N1[PassCopyrightReviewCmd.Handler::exec]
  N2[RetryPublicationReleaseSagaCmd.Handler]
  N3[RetryPublicationReleaseSagaCmd.Request]
  N4[PublicationReleaseReadiness::&lt;get-releaseSagaId&gt;]
  N5[PublicationReleaseReadiness::canRetryReleaseSaga]
  N1 -->|CommandSenderMethodToCommand| N3
  N2 -->|CommandHandlerToEntityMethod| N4
  N2 -->|CommandHandlerToEntityMethod| N5
  N3 -->|CommandToCommandHandler| N2
