flowchart TD
  N1[AdvancedReleaseReadinessController::passCopyright]
  N2[PassCopyrightReviewCmd.Request]
  N3[PublicationReleaseReadiness::passCopyrightReview]
  N1 -->|ControllerMethodToCommand| N2
  N2 -->|CommandToEntityMethod| N3

