flowchart TD
  N1[ContinuePublicationAfterMediaSucceededCmd.Handler]
  N2[ContinuePublicationAfterMediaSucceededCmd.Request]
  N3[MarkMediaProcessingSucceededCmd.Handler]
  N4[MarkMediaProcessingSucceededCmd.Request]
  N5[MediaProcessingSucceededDomainEventSubscriber::onMediaProcessingSucceeded]
  N6[MediaProcessingCallbackIntegrationEventSubscriber::onEvent]
  N7[Content::&lt;get-releasePolicy&gt;]
  N8[Content::&lt;get-releaseWindowClosesAt&gt;]
  N9[Content::&lt;get-releaseWindowOpensAt&gt;]
  N10[MediaProcessingTask::&lt;get-externalTaskId&gt;]
  N11[MediaProcessingTask::&lt;get-id&gt;]
  N12[MediaProcessingTask::&lt;get-processingStatus&gt;]
  N13[MediaProcessingTask::markSucceeded]
  N14[MediaProcessingSucceededDomainEvent]
  N1 -->|CommandHandlerToEntityMethod| N7
  N1 -->|CommandHandlerToEntityMethod| N8
  N1 -->|CommandHandlerToEntityMethod| N9
  N2 -->|CommandToCommandHandler| N1
  N3 -->|CommandHandlerToEntityMethod| N10
  N3 -->|CommandHandlerToEntityMethod| N11
  N3 -->|CommandHandlerToEntityMethod| N12
  N3 -->|CommandHandlerToEntityMethod| N13
  N4 -->|CommandToCommandHandler| N3
  N5 -->|DomainEventHandlerToCommand| N2
  N6 -->|CommandSenderMethodToCommand| N4
  N13 -->|EntityMethodToDomainEvent| N14
  N14 -->|DomainEventToHandler| N5

