flowchart TD
  N1[AdvancedPaidPublicationController::createPaid]
  N2[CreatePaidContentDraftCmd.Request]
  N3[ContentDraftCreatedDomainEventSubscriber::observeDraftCreation]
  N4[Content::&lt;get-id&gt;]
  N5[Content::onCreate]
  N6[ContentDraftCreatedDomainEvent]
  N1 -->|ControllerMethodToCommand| N2
  N2 -->|CommandToEntityMethod| N4
  N2 -->|CommandToEntityMethod| N5
  N5 -->|EntityMethodToDomainEvent| N6
  N6 -->|DomainEventToHandler| N3
