flowchart TD
  N1[GetMediaProcessingStatusCliHandler]
  N2[ListSubmittedMediaProcessingTasksForPollingQryHandler]
  N3[ContinuePublicationAfterMediaSucceededCmd.Handler]
  N4[ContinuePublicationAfterMediaSucceededCmd.Request]
  N5[MarkMediaProcessingSucceededCmd.Handler]
  N6[MarkMediaProcessingSucceededCmd.Request]
  N7[GetMediaProcessingStatusCli.Request]
  N8[MediaProcessingPollingFallbackJob::pollSubmittedTasks]
  N9[ListSubmittedMediaProcessingTasksForPollingQry.Request]
  N10[MediaProcessingSucceededDomainEventSubscriber::onMediaProcessingSucceeded]
  N11[Content::&lt;get-releasePolicy&gt;]
  N12[Content::&lt;get-releaseWindowClosesAt&gt;]
  N13[Content::&lt;get-releaseWindowOpensAt&gt;]
  N14[MediaProcessingTask::&lt;get-externalTaskId&gt;]
  N15[MediaProcessingTask::&lt;get-id&gt;]
  N16[MediaProcessingTask::&lt;get-processingStatus&gt;]
  N17[MediaProcessingTask::markSucceeded]
  N18[MediaProcessingSucceededDomainEvent]
  N3 -->|CommandHandlerToEntityMethod| N11
  N3 -->|CommandHandlerToEntityMethod| N12
  N3 -->|CommandHandlerToEntityMethod| N13
  N4 -->|CommandToCommandHandler| N3
  N5 -->|CommandHandlerToEntityMethod| N14
  N5 -->|CommandHandlerToEntityMethod| N15
  N5 -->|CommandHandlerToEntityMethod| N16
  N5 -->|CommandHandlerToEntityMethod| N17
  N6 -->|CommandToCommandHandler| N5
  N7 -->|CliToCliHandler| N1
  N8 -->|CommandSenderMethodToCommand| N6
  N8 -->|CliSenderMethodToCli| N7
  N8 -->|QuerySenderMethodToQuery| N9
  N9 -->|QueryToQueryHandler| N2
  N10 -->|DomainEventHandlerToCommand| N4
  N17 -->|EntityMethodToDomainEvent| N18
  N18 -->|DomainEventToHandler| N10

